version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: respondio
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  nodejs:
    build:
      context: .  # Path to your Node.js app Dockerfile
    container_name: my-nodejs
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
